import { useState } from "react"
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { useDashboardData } from "./_hooks/use-dashboard-data"

const COLORS = ["oklch(0.62 0.20 29)", "oklch(0.62 0.17 250)", "oklch(0.62 0.14 160)", "oklch(0.62 0.18 300)", "oklch(0.62 0.16 70)", "oklch(0.62 0.13 210)"]
const months = Array.from({ length: 12 }, (_, month) => new Intl.DateTimeFormat("es-PE", { month: "long" }).format(new Date(2026, month, 1)))
const number = new Intl.NumberFormat("es-PE")

export function DashboardPage() {
  const today = new Date()
  const [period, setPeriod] = useState<"month" | "year">("year")
  const [year, setYear] = useState(today.getFullYear())
  const [month, setMonth] = useState(today.getMonth() + 1)
  const dashboard = useDashboardData({ period, year, ...(period === "month" ? { month } : {}), timezone: "America/Lima" })
  const data = dashboard.data
  const title = period === "month" ? `${capitalize(months[month - 1])} de ${year}` : `Año ${year}`

  return <div className="space-y-6 pb-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-xl font-semibold tracking-tight">Dashboard</h1><p className="mt-1 text-sm text-muted-foreground">{title} · Métricas consolidadas en America/Lima</p></div>{data && <div className="flex gap-6"><Metric label="Enrolamientos" value={data.summary.enrollmentEvents} /><Metric label="Sesiones" value={data.summary.sessions} /><Metric label="Activos" value={data.summary.activePatients} /></div>}</div>
    <div className="flex flex-wrap items-center gap-3"><div className="flex gap-1">{(["month", "year"] as const).map((value) => <Button key={value} size="sm" variant={period === value ? "default" : "outline"} className="rounded-full" onClick={() => setPeriod(value)}>{value === "month" ? "Mes" : "Año"}</Button>)}</div><Select value={String(year)} onValueChange={(value) => setYear(Number(value))}><SelectTrigger className="h-8 w-28"><SelectValue /></SelectTrigger><SelectContent>{yearOptions(year).map((value) => <SelectItem key={value} value={String(value)}>{value}</SelectItem>)}</SelectContent></Select>{period === "month" && <Select value={String(month)} onValueChange={(value) => setMonth(Number(value))}><SelectTrigger className="h-8 w-36"><SelectValue /></SelectTrigger><SelectContent>{months.map((name, index) => <SelectItem key={name} value={String(index + 1)}>{capitalize(name)}</SelectItem>)}</SelectContent></Select>}</div>
    {dashboard.isLoading && <Loading />}
    {dashboard.isError && <Card><CardHeader><CardTitle>No se pudo cargar el dashboard</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{dashboard.error instanceof Error ? dashboard.error.message : "Verifica la conexión con el servidor."}</CardContent></Card>}
    {data && <><section className="grid gap-6 xl:grid-cols-2"><DistributionCard title="Diagnósticos actuales" data={data.distributions.diagnoses} /><DistributionCard title="Tratamientos actuales" data={data.distributions.treatments} /></section><section className="grid gap-6 xl:grid-cols-[1.45fr_1fr]"><Card><CardHeader><CardTitle>Evolución de enrolamientos</CardTitle></CardHeader><CardContent><TrendChart data={data.trend} /></CardContent></Card><DistributionCard title="Estadios de cáncer" data={data.distributions.cancerStages} /></section><section className="grid gap-6 xl:grid-cols-[1fr_1fr_1fr]"><DistributionCard title="Género" data={data.distributions.gender} /><Card><CardHeader><CardTitle>Continuidad</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Metric label="Completadas" value={data.summary.completedSessions} /><Metric label="Tasa de completitud" value={`${data.summary.completionRate}%`} /><Metric label="Bajas" value={data.summary.dropoutPatients} /><Metric label="Fallecidos" value={data.summary.deceasedPatients} /></CardContent></Card><Card><CardHeader><CardTitle>Cohorte</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Metric label="Pacientes" value={data.summary.cohortPatients} /><Metric label="Inactivos" value={data.summary.inactivePatients} /></CardContent></Card></section><section className="grid gap-6 xl:grid-cols-2"><TableCard title="Hospitales con más pacientes" header="Hospital" data={data.hospitals} /><TableCard title="Regiones con mayor movimiento" header="Región" data={data.regions} /></section></>}
  </div>
}

function Metric({ label, value }: { label: string; value: number | string }) { return <div className="text-center"><p className="text-2xl font-semibold tabular-nums">{typeof value === "number" ? number.format(value) : value}</p><p className="text-xs text-muted-foreground">{label}</p></div> }
function DistributionCard({ title, data }: { title: string; data: { label: string; count: number }[] }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{data.length === 0 ? <Empty /> : <div className="grid gap-4 lg:grid-cols-[240px_1fr]"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="count" nameKey="label" innerRadius={62} outerRadius={96} paddingAngle={2}>{data.map((item, index) => <Cell key={item.label} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="space-y-2">{data.map((item, index) => <div key={item.label} className="flex justify-between gap-3 text-sm"><span className="truncate"><span className="mr-2 inline-block size-2.5 rounded-full" style={{ backgroundColor: COLORS[index % COLORS.length] }} />{item.label}</span><b>{number.format(item.count)}</b></div>)}</div></div>}</CardContent></Card> }
function TrendChart({ data }: { data: { period: string; enrollmentEvents: number; sessions: number; completedSessions: number }[] }) { return <div className="h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="period" tickLine={false} axisLine={false} /><YAxis tickLine={false} axisLine={false} /><Tooltip /><Area type="monotone" dataKey="enrollmentEvents" name="Enrolamientos" stroke="var(--chart-2)" fill="var(--chart-2)" fillOpacity={0.14} strokeWidth={2.5} /><Area type="monotone" dataKey="sessions" name="Sesiones" stroke="var(--chart-1)" fill="var(--chart-1)" fillOpacity={0.08} strokeWidth={2} /></AreaChart></ResponsiveContainer></div> }
function TableCard({ title, header, data }: { title: string; header: string; data: { name: string; count: number }[] }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="p-0">{data.length === 0 ? <Empty /> : <Table><TableHeader><TableRow><TableHead>{header}</TableHead><TableHead className="text-right">Pacientes</TableHead></TableRow></TableHeader><TableBody>{data.map((item) => <TableRow key={item.name}><TableCell className="font-medium">{item.name}</TableCell><TableCell className="text-right">{number.format(item.count)}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card> }
function Empty() { return <div className="flex h-40 items-center justify-center text-sm text-muted-foreground">No hay datos para este periodo.</div> }
function Loading() { return <div className="grid gap-6 md:grid-cols-2">{Array.from({ length: 4 }).map((_, index) => <Card key={index}><CardContent className="h-48 animate-pulse bg-muted/30" /></Card>)}</div> }
function yearOptions(current: number) { return Array.from({ length: 7 }, (_, index) => current - index) }
function capitalize(value: string) { return value.charAt(0).toUpperCase() + value.slice(1) }
