import { useForm, Controller } from "react-hook-form"; import { zodResolver } from "@hookform/resolvers/zod"; import { z } from "zod"
import { Label } from "@/components/ui/label"; import { Input } from "@/components/ui/input"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { CreditCard, MapPin, Phone, GraduationCap, ShieldCheck } from "lucide-react"
import { useEnrollmentStore, PERU_DEPARTAMENTOS } from "../../_store/enrollment-store"
import { StepHeader, SectionHeader, StepNav } from "../shared"
const schema=z.object({q9_nombrePaciente:z.string().min(1,"Requerido"),q10_dni:z.string().min(8,"DNI inválido"),q11_fechaNacimiento:z.string().min(1,"Requerido"),sexo:z.string().min(1,"Requerido"),q12_lugarNacimiento:z.string().min(1,"Requerido"),q13_direccion:z.string().min(1,"Requerido"),q14_departamentoResidencia:z.string().min(1,"Requerido"),zonificacion:z.string().min(1,"Requerido"),q15_tiempoHospital:z.string(),q16_dniCoincide:z.string().min(1,"Requerido"),q17_telefono:z.string().min(1,"Requerido"),q18_telefonoAuxiliar:z.string(),q19_telefonoFamiliar:z.string(),q20_nombreFamiliar:z.string(),generoCuidador:z.string(),q21_tieneWhatsapp:z.string().min(1,"Requerido"),q22_gradoInstruccion:z.string().min(1,"Requerido"),q23_lenguaOriginaria:z.string().min(1,"Requerido"),q24_requiereTraduccion:z.string().min(1,"Requerido"),q25_tieneSeguro:z.string().min(1,"Requerido"),q26_tipoSeguro:z.string(),puntoIngreso:z.string()})
const fl="text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground/70";const ic="bg-card border focus-visible:ring-1 focus-visible:ring-primary/40";const sc="w-full bg-card border focus-visible:ring-1 focus-visible:ring-primary/40"
const GRADOS=["Inicial","Primaria incompleta","Primaria","Secundaria incompleta","Secundaria","Educación técnica","Educación Técnica incompleta","Educación superior","Educación superior incompleta","No cuenta con grado de instrucción"];const LENGUAS=["Castellano/Español","Quechua","Aymara","Lengua de señas","Otros"];const SEGUROS=["SIS","EsSalud","EPS - Essalud","Fuerzas Armadas","Saludpol","Privado"];const PUNTOS=["Llamada directa","Referido por paciente","Referido por voluntario","Redes sociales FPC","Campaña de prevención","Centro de salud / hospital","Otro"]
function FE({msg}:{msg?:string}){if(!msg)return null;return<p className="text-destructive text-xs">{msg}</p>}

export function Step5Datos(){const{formData,saveStepData,nextStep,prevStep}=useEnrollmentStore();const p=formData
const{register,control,handleSubmit,watch,formState:{errors}}=useForm({resolver:zodResolver(schema),defaultValues:{q9_nombrePaciente:p.q9_nombrePaciente??"",q10_dni:p.q10_dni??"",q11_fechaNacimiento:p.q11_fechaNacimiento??"",sexo:p.sexo??"",q12_lugarNacimiento:p.q12_lugarNacimiento??"",q13_direccion:p.q13_direccion??"",q14_departamentoResidencia:p.q14_departamentoResidencia??"",zonificacion:p.zonificacion??"",q15_tiempoHospital:p.q15_tiempoHospital??"",q16_dniCoincide:p.q16_dniCoincide??"",q17_telefono:p.q17_telefono??"",q18_telefonoAuxiliar:p.q18_telefonoAuxiliar??"",q19_telefonoFamiliar:p.q19_telefonoFamiliar??"",q20_nombreFamiliar:p.q20_nombreFamiliar??"",generoCuidador:p.generoCuidador??"",q21_tieneWhatsapp:p.q21_tieneWhatsapp??"",q22_gradoInstruccion:p.q22_gradoInstruccion??"",q23_lenguaOriginaria:p.q23_lenguaOriginaria??"",q24_requiereTraduccion:p.q24_requiereTraduccion??"",q25_tieneSeguro:p.q25_tieneSeguro??"",q26_tipoSeguro:p.q26_tipoSeguro??"",puntoIngreso:p.puntoIngreso??""}})
const tieneSeguro=watch("q25_tieneSeguro")
return<form onSubmit={handleSubmit(v=>{saveStepData(v);nextStep()})} className="flex flex-col gap-10">
<StepHeader step={5} title="Datos del Paciente" description="Complete los datos de identidad y contacto del paciente." />
<section className="flex flex-col gap-5"><SectionHeader icon={CreditCard} title="Información de Identidad" />
<div className="grid grid-cols-2 gap-4"><div className="flex flex-col gap-2"><Label className={fl}>DNI <span className="text-destructive">*</span></Label><Input placeholder="74829304" className={ic} {...register("q10_dni")} /><FE msg={errors.q10_dni?.message}/></div><div className="flex flex-col gap-2"><Label className={fl}>Fecha de nacimiento <span className="text-destructive">*</span></Label><Input type="date" className={ic} {...register("q11_fechaNacimiento")} /><FE msg={errors.q11_fechaNacimiento?.message}/></div></div>
<div className="flex flex-col gap-2"><Label className={fl}>Nombre completo <span className="text-destructive">*</span></Label><Input placeholder="Tal como aparece en el DNI" className={ic} {...register("q9_nombrePaciente")} /><FE msg={errors.q9_nombrePaciente?.message}/></div>
<div className="flex flex-col gap-2"><Label className={fl}>Sexo <span className="text-destructive">*</span></Label><Controller name="sexo" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent><SelectItem value="Femenino">Femenino</SelectItem><SelectItem value="Masculino">Masculino</SelectItem><SelectItem value="Intersexual">Intersexual</SelectItem><SelectItem value="Prefiere no decir">Prefiere no decir</SelectItem></SelectContent></Select>)} /><FE msg={errors.sexo?.message}/></div></section>
<section className="flex flex-col gap-5"><SectionHeader icon={MapPin} title="Residencia y Origen" />
<div className="grid grid-cols-2 gap-4"><div className="flex flex-col gap-2"><Label className={fl}>Lugar de nacimiento <span className="text-destructive">*</span></Label><Controller name="q12_lugarNacimiento" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Departamento..." /></SelectTrigger><SelectContent>{[...PERU_DEPARTAMENTOS,"VENEZUELA","Otros"].map(d=><SelectItem key={d} value={d}>{d}</SelectItem>)}</SelectContent></Select>)} /><FE msg={errors.q12_lugarNacimiento?.message}/></div><div className="flex flex-col gap-2"><Label className={fl}>Departamento de residencia <span className="text-destructive">*</span></Label><Controller name="q14_departamentoResidencia" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Departamento..." /></SelectTrigger><SelectContent>{PERU_DEPARTAMENTOS.map(d=><SelectItem key={d} value={d}>{d}</SelectItem>)}</SelectContent></Select>)} /><FE msg={errors.q14_departamentoResidencia?.message}/></div></div>
<div className="flex flex-col gap-2"><Label className={fl}>Dirección y distrito <span className="text-destructive">*</span></Label><Input placeholder="Calle, número, distrito" className={ic} {...register("q13_direccion")} /><FE msg={errors.q13_direccion?.message}/></div>
<div className="flex flex-col gap-2"><Label className={fl}>Zonificación <span className="text-destructive">*</span></Label><Controller name="zonificacion" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent><SelectItem value="Urbano">Urbano</SelectItem><SelectItem value="Rural">Rural</SelectItem></SelectContent></Select>)} /><FE msg={errors.zonificacion?.message}/></div>
<div className="grid grid-cols-2 gap-4"><div className="flex flex-col gap-2"><Label className={fl}>Tiempo al hospital</Label><Input placeholder="Ej: 30 min" className={ic} {...register("q15_tiempoHospital")} /></div><div className="flex flex-col gap-2"><Label className={fl}>¿DNI coincide con domicilio? <span className="text-destructive">*</span></Label><Controller name="q16_dniCoincide" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent><SelectItem value="Si">Sí</SelectItem><SelectItem value="No">No</SelectItem></SelectContent></Select>)} /><FE msg={errors.q16_dniCoincide?.message}/></div></div></section>
<section className="flex flex-col gap-5"><SectionHeader icon={Phone} title="Información de Contacto" />
<div className="grid grid-cols-2 gap-4"><div className="flex flex-col gap-2"><Label className={fl}>Teléfono principal <span className="text-destructive">*</span></Label><Input placeholder="9XX XXX XXX" className={ic} {...register("q17_telefono")} /><FE msg={errors.q17_telefono?.message}/></div><div className="flex flex-col gap-2"><Label className={fl}>Teléfono auxiliar</Label><Input placeholder="9XX XXX XXX" className={ic} {...register("q18_telefonoAuxiliar")} /></div></div>
<div className="grid grid-cols-2 gap-4"><div className="flex flex-col gap-2"><Label className={fl}>Teléfono familiar</Label><Input placeholder="9XX XXX XXX" className={ic} {...register("q19_telefonoFamiliar")} /></div><div className="flex flex-col gap-2"><Label className={fl}>Nombre del familiar</Label><Input placeholder="Nombre y apellidos" className={ic} {...register("q20_nombreFamiliar")} /></div></div>
<div className="flex flex-col gap-2"><Label className={fl}>Género del cuidador</Label><Controller name="generoCuidador" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent><SelectItem value="Femenino">Femenino</SelectItem><SelectItem value="Masculino">Masculino</SelectItem><SelectItem value="Otro">Otro</SelectItem><SelectItem value="No aplica">No aplica</SelectItem></SelectContent></Select>)} /></div>
<div className="flex flex-col gap-2"><Label className={fl}>¿Tiene WhatsApp? <span className="text-destructive">*</span></Label><Controller name="q21_tieneWhatsapp" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent><SelectItem value="Sí">Sí</SelectItem><SelectItem value="No">No</SelectItem></SelectContent></Select>)} /><FE msg={errors.q21_tieneWhatsapp?.message}/></div></section>
<section className="flex flex-col gap-5"><SectionHeader icon={GraduationCap} title="Perfil Socioeducativo" />
<div className="flex flex-col gap-2"><Label className={fl}>Grado de instrucción <span className="text-destructive">*</span></Label><Controller name="q22_gradoInstruccion" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent>{GRADOS.map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select>)} /><FE msg={errors.q22_gradoInstruccion?.message}/></div>
<div className="grid grid-cols-2 gap-4"><div className="flex flex-col gap-2"><Label className={fl}>Lengua originaria <span className="text-destructive">*</span></Label><Controller name="q23_lenguaOriginaria" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent>{LENGUAS.map(l=><SelectItem key={l} value={l}>{l}</SelectItem>)}</SelectContent></Select>)} /><FE msg={errors.q23_lenguaOriginaria?.message}/></div><div className="flex flex-col gap-2"><Label className={fl}>¿Requiere traducción? <span className="text-destructive">*</span></Label><Controller name="q24_requiereTraduccion" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent><SelectItem value="Sí">Sí</SelectItem><SelectItem value="No">No</SelectItem></SelectContent></Select>)} /><FE msg={errors.q24_requiereTraduccion?.message}/></div></div></section>
<section className="flex flex-col gap-5"><SectionHeader icon={ShieldCheck} title="Seguro de Salud" />
<div className="flex flex-col gap-2"><Label className={fl}>¿Cuenta con seguro? <span className="text-destructive">*</span></Label><Controller name="q25_tieneSeguro" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent><SelectItem value="Si">Sí</SelectItem><SelectItem value="No">No</SelectItem></SelectContent></Select>)} /><FE msg={errors.q25_tieneSeguro?.message}/></div>
{tieneSeguro==="Si"&&<div className="flex flex-col gap-2"><Label className={fl}>Tipo de seguro</Label><Controller name="q26_tipoSeguro" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent>{SEGUROS.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>)} /></div>}
<div className="flex flex-col gap-2"><Label className={fl}>Punto de ingreso al programa</Label><Controller name="puntoIngreso" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent>{PUNTOS.map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select>)} /></div></section>
<StepNav currentStep={5} onPrev={prevStep} /></form>}
