import { useForm, Controller } from "react-hook-form"; import { zodResolver } from "@hookform/resolvers/zod"; import { z } from "zod"; import { useMutation } from "@tanstack/react-query"
import { Label } from "@/components/ui/label"; import { Input } from "@/components/ui/input"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Button } from "@/components/ui/button"; import { CheckCircle2, Clock, ClipboardCheck } from "lucide-react"
import { patientsApi } from "@/lib/api"; import { useAuthStore } from "@/store/auth-store"; import { useEnrollmentStore } from "../../_store/enrollment-store"
import { StepHeader, SectionHeader, StepNav } from "../shared"; import { toast } from "sonner"
const schema=z.object({q132_encuestaAceptada:z.string().min(1,"Requerido"),q133_horaFin:z.string().min(1,"Requerido")})
export function Step8Cierre(){const{formData,saveStepData,prevStep,completeEnrollment,resetEnrollment,isComplete}=useEnrollmentStore();const p=formData;const user=useAuthStore(s=>s.user);const now=new Date().toTimeString().slice(0,5)
const{control,register,handleSubmit}=useForm({resolver:zodResolver(schema),defaultValues:{q132_encuestaAceptada:p.q132_encuestaAceptada??"",q133_horaFin:p.q133_horaFin??now}})
const mutation=useMutation({mutationFn:async()=>{await patientsApi.enroll({patientId:null,patientData:{fullName:p.q9_nombrePaciente||"",dni:p.q10_dni||null,birthDate:p.q11_fechaNacimiento||null,primaryPhone:p.q17_telefono||"",secondaryPhone:p.q18_telefonoAuxiliar||null,hasWhatsapp:p.q21_tieneWhatsapp==="Sí",role:"PATIENT"},details:{birthDepartment:p.q12_lugarNacimiento||null,currentAddress:p.q13_direccion||null,currentDepartment:p.q14_departamentoResidencia||null,dniMatchesAddress:p.q16_dniCoincide==="Si"?true:p.q16_dniCoincide==="No"?false:null,travelTimeToHospital:p.q15_tiempoHospital||null,emergencyContactName:p.q20_nombreFamiliar||null,emergencyContactPhone:p.q19_telefonoFamiliar||null,nativeLanguage:p.q23_lenguaOriginaria||null,requiresTranslation:p.q24_requiereTraduccion==="Sí"},insurance:p.q25_tieneSeguro==="Si"?{insuranceType:(p.q26_tipoSeguro?.includes("SIS")?"SIS":p.q26_tipoSeguro?.includes("EsSalud")?"ESSALUD":"NONE") as any,isCurrent:true}:undefined,symptomReport:{hasDiscomfort:p.q28_malestares==="Sí",signsAndSymptoms:p.q30_signosSintomas||p.q44_signosSintomas_eps||p.q59_signosSintomas_ns||null},diagnosis:(p.q38_diagnostico||p.q51_diagnostico_eps||p.q_tipoCancer_ds)&&p.q_tipoCancer_ds?{diagnosis:(p.q38_diagnostico||p.q51_diagnostico_eps||p.q_tipoCancer_ds)||"",isCurrent:true}:undefined,enrollmentMetadata:{caseComments:p.q1_comentarios||null,startTime:p.q2_horaInicio?`2025-01-01T${p.q2_horaInicio}:00`:null,endTime:p.q133_horaFin?`2025-01-01T${p.q133_horaFin}:00`:null,dataPolicyAccepted:p.q3_acuerdo==="Sí",informedConsentAccepted:p.q8_consentimiento==="Acepto",isOncologicalPatient:p.q5_esPacienteOnco==="Sí",programEntryPoint:p.puntoIngreso||null,surveyAccepted:p.q132_encuestaAceptada==="Sí",agentId:user?.id,affiliationType:p.q4_tipo==="Para mi"?"PATIENT":"FAMILY"}})},onSuccess:()=>{completeEnrollment();toast.success("Paciente enrolado correctamente")},onError:(err:Error)=>{toast.error("Error",{description:err.message})}})
if(isComplete)return<div className="flex flex-col items-center justify-center py-16 text-center"><div className="mb-5 flex size-20 items-center justify-center rounded-full bg-emerald-500/10 ring-8 ring-emerald-500/5"><CheckCircle2 className="size-10 text-emerald-500" /></div><p className="mb-1 text-[10px] font-bold tracking-widest text-emerald-600 uppercase">Inscripción completada</p><h2 className="mb-3 text-2xl font-bold">Registro exitoso</h2><p className="mb-8 max-w-sm text-sm text-muted-foreground">El paciente ha sido registrado en el Programa SEPA.</p><Button onClick={resetEnrollment} size="lg" className="px-8">Nueva inscripción</Button></div>
return<form onSubmit={handleSubmit(v=>{saveStepData(v);mutation.mutate()})} className="flex flex-col gap-8">
<StepHeader step={8} title="Cierre de Llamada" description="Registre el cierre y confirme la encuesta." />
<div className="rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-5"><p className="mb-3 text-[10px] font-bold tracking-widest text-emerald-700/80 uppercase">Resumen</p><div className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm"><span className="text-muted-foreground/60 text-[10px] font-bold tracking-wide uppercase">Paciente</span><span className="font-medium">{p.q9_nombrePaciente??"—"}</span><span className="text-muted-foreground/60 text-[10px] font-bold tracking-wide uppercase">DNI</span><span className="font-medium">{p.q10_dni??"—"}</span><span className="text-muted-foreground/60 text-[10px] font-bold tracking-wide uppercase">Categoría</span><span className="font-medium">{p.q27_categoria??"—"}</span><span className="text-muted-foreground/60 text-[10px] font-bold tracking-wide uppercase">Inicio</span><span className="font-medium">{p.q2_horaInicio??"—"}</span></div></div>
<section className="flex flex-col gap-5"><SectionHeader icon={ClipboardCheck} title="Encuesta" /><div className="flex flex-col gap-2"><Label className="text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground/70">¿Acepta la encuesta? <span className="text-destructive">*</span></Label><Controller name="q132_encuestaAceptada" control={control} render={({field})=>(<Select value={field.value} onValueChange={field.onChange}><SelectTrigger className="w-full bg-card border"><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent><SelectItem value="Sí">Sí, acepta</SelectItem><SelectItem value="No">No desea</SelectItem></SelectContent></Select>)} /></div></section>
<section className="flex flex-col gap-5"><SectionHeader icon={Clock} title="Registro de Tiempo" /><div className="flex flex-col gap-2"><Label className="text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground/70">Hora de fin <span className="text-destructive">*</span></Label><Input type="time" className="max-w-48 bg-card border" {...register("q133_horaFin")} /></div></section>
{mutation.isError&&<div className="border-destructive/20 bg-destructive/5 rounded-xl border p-4"><p className="text-destructive text-sm">Error al guardar.</p></div>}
<StepNav currentStep={8} onPrev={prevStep} isLast isLoading={mutation.isPending} /></form>}
