import { useForm, Controller } from "react-hook-form"; import { Label } from "@/components/ui/label"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Activity, Stethoscope, HeartPulse } from "lucide-react"
import { useEnrollmentStore, Q27_BRANCH_MAP, BRANCH_LABELS } from "../../_store/enrollment-store"
import { StepHeader, SectionHeader, StepNav } from "../shared"
const fl="text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground/70";const sc="w-full bg-card border";const EPS=["PACIFICO SEGUROS","RIMAC SEGUROS","MAPFRE SEGUROS","POSITIVA SEGUROS","SANITAS","ONCOSALUD","Otros"];const CANCER=["Mama","Cervicouterino","Pulmón","Próstata","Colon / Recto","Leucemia","Linfoma","Estómago","Piel","Tiroides","Hígado","Páncreas","Ovario","Otros"];const SIT=["En tratamiento","Pendiente inicio","Suspendido","Finalizado"]
function F({l,c,e}:{l:string;c:React.ReactNode;e?:string}){return<div className="flex flex-col gap-2"><Label className={fl}>{l}</Label>{c}{e&&<p className="text-destructive text-xs">{e}</p>}</div>}
function YN({n,ctrl}:{n:string;ctrl:any}){return<Controller name={n} control={ctrl} render={({field}:any)=>(<Select value={field.value||""} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent><SelectItem value="Sí">Sí</SelectItem><SelectItem value="No">No</SelectItem></SelectContent></Select>)} />}
function TF({n,ctrl,ph,multi}:{n:string;ctrl:any;ph?:string;multi?:boolean}){return<Controller name={n} control={ctrl} render={({field}:any)=>multi?<Textarea placeholder={ph} value={field.value||""} onChange={e=>field.onChange(e.target.value)} className="bg-card border" />:<Input placeholder={ph} value={field.value||""} onChange={e=>field.onChange(e.target.value)} className="bg-card border" />} />}
function BSignos({ctrl}:{ctrl:any}){return<div className="flex flex-col gap-8"><section className="flex flex-col gap-5"><SectionHeader icon={Activity} title="Signos y Síntomas" /><div className="grid grid-cols-2 gap-4"><F l="¿Ha presentado malestar?" c={<YN n="q28_malestares" ctrl={ctrl} />} /><F l="¿Solicitó consulta médica?" c={<YN n="q31_solicitoConsulta" ctrl={ctrl} />} /></div><F l="¿Qué signos o síntomas presentó?" c={<TF n="q30_signosSintomas" ctrl={ctrl} ph="Describa..." multi />} /><F l="Comentarios" c={<TF n="q29_comentarios_ss" ctrl={ctrl} ph="Comentarios..." multi />} /></section></div>}
function BSignosEPS({ctrl}:{ctrl:any}){return<div className="flex flex-col gap-8"><section className="flex flex-col gap-5"><SectionHeader icon={Activity} title="Datos del Seguro EPS" /><F l="EPS del paciente" c={<Controller name="q43_eps" control={ctrl} render={({field}:any)=>(<Select value={field.value||""} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar EPS..." /></SelectTrigger><SelectContent>{EPS.map(e=><SelectItem key={e} value={e}>{e}</SelectItem>)}</SelectContent></Select>)} />} /><F l="¿Qué signos o síntomas presentó?" c={<TF n="q44_signosSintomas_eps" ctrl={ctrl} ph="Describa..." multi />} /><F l="¿Le brindaron diagnóstico?" c={<TF n="q51_diagnostico_eps" ctrl={ctrl} ph="Diagnóstico" />} /><F l="¿Recibe tratamiento?" c={<YN n="q53_tieneTratamiento_eps" ctrl={ctrl} />} /></section></div>}
function BSignosNS({ctrl}:{ctrl:any}){return<div className="flex flex-col gap-8"><section className="flex flex-col gap-5"><SectionHeader icon={Activity} title="Signos y Síntomas" /><F l="¿Cuándo podría afiliarse al SIS?" c={<TF n="q55_cuandoAfiliarseSis_ns" ctrl={ctrl} ph="Fecha o periodo" />} /><F l="Motivo de no afiliarse" c={<TF n="q57_motivoNoAfiliarseSis_ns" ctrl={ctrl} ph="Detalle" multi />} /><F l="¿Ha presentado malestar?" c={<YN n="q58_malestares_ns" ctrl={ctrl} />} /><F l="¿Qué signos o síntomas?" c={<TF n="q59_signosSintomas_ns" ctrl={ctrl} ph="Describa..." multi />} /></section></div>}
function BDx({branch,ctrl}:{branch:string;ctrl:any}){const p=branch==="dx_eps"?"de":branch==="dx_noseguro"?"dn":"ds";return<div className="flex flex-col gap-8"><section className="flex flex-col gap-5"><SectionHeader icon={Stethoscope} title="Diagnóstico Oncológico" /><div className="grid grid-cols-2 gap-4"><F l="Tipo de cáncer" c={<Controller name={`q_tipoCancer_${p}`} control={ctrl} render={({field}:any)=>(<Select value={field.value||""} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent>{CANCER.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select>)} />} /><F l="Estadio" c={<TF n={`q_estadio_${p}`} ctrl={ctrl} ph="1, 2, 3, 4 o desconoce" />} /></div><F l="Síntoma que llevó al chequeo" c={<TF n={`q_sintomaChequeo_${p}`} ctrl={ctrl} ph="Motivo" multi />} /><div className="grid grid-cols-2 gap-4"><F l="Fecha de diagnóstico" c={<TF n={`q_fechaDx_${p}`} ctrl={ctrl} ph="Fecha" />} /><F l="Tiempo de espera" c={<TF n={`q_tiempoEsperaDx_${p}`} ctrl={ctrl} ph="Ej: 6 semanas" />} /></div><F l="¿Recibe tratamiento?" c={<YN n={`q_recibeTratamiento_${p}`} ctrl={ctrl} />} /><div className="grid grid-cols-2 gap-4"><F l="Tipo de tratamiento" c={<TF n={`q_tipoTratamiento_${p}`} ctrl={ctrl} ph="Ej: Quimio" />} /><F l="Situación" c={<Controller name={`q_situacionTratamiento_${p}`} control={ctrl} render={({field}:any)=>(<Select value={field.value||""} onValueChange={field.onChange}><SelectTrigger className={sc}><SelectValue placeholder="Seleccionar..." /></SelectTrigger><SelectContent>{SIT.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>)} />} /></div></section><section className="flex flex-col gap-5"><SectionHeader icon={HeartPulse} title="Servicios de Apoyo" /><F l="¿Desea soporte emocional (psicooncología)?" c={<YN n={`q_psico_${p}`} ctrl={ctrl} />} /></section></div>}
function BPsico({ctrl}:{ctrl:any}){return<div className="flex flex-col gap-8"><section className="flex flex-col gap-5"><SectionHeader icon={HeartPulse} title="Situación Emocional" /><F l="Termómetro emocional (1-10)" c={<TF n="q130_medicacion_p" ctrl={ctrl} ph="Ej: 7" />} /><F l="¿Llamada o videollamada?" c={<TF n="q131_comentariosEmo_p" ctrl={ctrl} ph="Preferencia" multi />} /></section></div>}
function BFPC({ctrl}:{ctrl:any}){return<div className="flex flex-col gap-8"><section className="flex flex-col gap-5"><SectionHeader icon={Activity} title="Servicio Requerido" /><F l="Servicio FPC requerido" c={<TF n="q123_servicioFPC" ctrl={ctrl} ph="Describa..." multi />} /><F l="¿Familiares para charlas?" c={<YN n="q124_charlasEduc" ctrl={ctrl} />} /></section></div>}
function BOtros({ctrl}:{ctrl:any}){return<div className="flex flex-col gap-5"><SectionHeader icon={Activity} title="Descripción de la Consulta" /><F l="Motivo" c={<TF n="q_otros_descripcion" ctrl={ctrl} ph="Describa..." multi />} /><F l="Acciones tomadas" c={<TF n="q_otros_acciones" ctrl={ctrl} ph="Acciones..." multi />} /></div>}

export function Step7Atencion(){const{formData,saveStepData,nextStep,prevStep}=useEnrollmentStore();const p=formData;const cat=p.q27_categoria??"";const branch=Q27_BRANCH_MAP[cat];const bl=branch?BRANCH_LABELS[branch]:cat;const{control,handleSubmit}=useForm({defaultValues:p as Record<string,string>})
return<form onSubmit={handleSubmit(v=>{saveStepData(v as any);nextStep()})} className="flex flex-col gap-8">
<StepHeader step={7} title="Atención Especializada" description={`Rama activa: ${bl}`} />
<div className="bg-card rounded-xl px-4 py-3"><p className="text-muted-foreground/60 text-[10px] font-bold tracking-widest uppercase">Categoría seleccionada</p><p className="text-foreground mt-0.5 text-sm font-semibold">{bl}</p></div>
{branch==="signos_seguro"?<BSignos ctrl={control} />:branch==="signos_eps"?<BSignosEPS ctrl={control} />:branch==="signos_noseguro"?<BSignosNS ctrl={control} />:branch==="dx_seguro"||branch==="dx_eps"||branch==="dx_noseguro"?<BDx branch={branch} ctrl={control} />:branch==="psico"?<BPsico ctrl={control} />:branch==="fpc"?<BFPC ctrl={control} />:<BOtros ctrl={control} />}
<StepNav currentStep={7} onPrev={prevStep} /></form>}
